### PR TITLE
Allow Cypress 11

### PR DESCRIPTION
**Pull request by dmaicher**
See https://github.com/4teamwork/cypress-drag-drop/issues/121

### CODE REVIEW

**Review by dpschen — APPROVED** [review]

**Comment by vaibhavganatra** [comment]
@dmaicher Can you please merge this PR so we can upgrade to cypress 11 and continue to use this drag and drop package?

**Comment by bierik** [comment]
@dmaicher Could you also update the cypress version in the package.json: https://github.com/4teamwork/cypress-drag-drop/blob/master/package.json#L37, so the test will run against the new version of cypress. Thank you so much for your contribution.

**Comment by bierik** [comment]
@dmaicher You also have to update the `yarn.lock` file. Simply to `yarn install`, this should fix the issue.

**Comment by dmaicher** [comment]
Wondering why we need a lock file committed into the repository? :thinking: Do you think it can be removed?

**Comment by bierik** [comment]
This PR is not about discussing whether a lockfile is needed or not, it is required by the build process though. Please refer to this article for example, which tells you why a lockfile is useful in software engineering projects. The main reason is, that you are not guaranteed to install exactly the same versions as your coworkers for example with just a package.json.

**Comment by dmaicher** [comment]
Ok thanks. I'm familiar with https://developerexperience.io/practices/lockfile and also disagree with it for library projects like this one. But anyway thanks for your reply and your reasoning behind using a lockfile. I don't want to start an argument :blush: 

Let me setup Yarn locally quickly and update the lockfile then.

**Comment by bierik** [comment]
Thank you so much. The tests seem to be passing. Could you clean up the git history. I'd squash every commit in the first one, so we just have `Allow Cypress 11` in the history. Then we are ready to merge 😃.

**Comment by vaibhavganatra** [comment]
@bierik Could you please merge this and create a new 2.2.2 release so we can upgrade to 11.1.0? TIA

**Pull request merged**
